version: '3.8'

services:
  hifazat-ai:
    build: 
      context: .
      dockerfile: Dockerfile
    image: hifazat-ai:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=4
      - MKL_NUM_THREADS=4
      - NUMEXPR_NUM_THREADS=4
      - OPENBLAS_NUM_THREADS=4
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./backend/media:/app/backend/media
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for i5 6th gen target
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '4'
        reservations:
          memory: 2G
          cpus: '2'

  # Optional: Add database service
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: hifazat
  #     POSTGRES_USER: hifazat
  #     POSTGRES_PASSWORD: secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

  # Optional: Add Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis_data:/data

volumes:
  # postgres_data:
  # redis_data:
  data:
  logs:
  models: